### ISSUE TITLE
MQTT Reboot

### ISSUE THREAD

**Issue by Rustymage** [g8keeperzuul/wz_mini_hacks-MQTT#2]
Installed as per instructions.

Every time I change a setting via MQTT on Home Assistant, the camera reboots.

Tell me what you need to help understand this issue and I'll do my best to provide.

Thanks in advance.

**Comment by g8keeperzuul** [comment]
With the exception of playing a sound, updating the refresh rate and enabling or disabling the web console, **ALL other changes in state require that the camera be rebooted before the change takes effect**. This reboot is automatically done, but it does mean there is usually at least 5 seconds before the update takes effect. It also means that multiple update requests need to be spaced out with an appropriate delay to allow the camera to recycle before being able to accept the next request. _Not ideal, but due to the limitations of the wz_mini_hack, the best we can do for now._

**Comment by Rustymage** [comment]
Understood and it was more an observation in case it wasn't normal.

Thank you!

😀
